services:
  stats-server:
    ports:
      - "9090:9090"
    build: ./stat-service/stat-server
    image: stats-server-image
    container_name: stats-server-container
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user

  stats-db:
    image: postgres:16.1
    container_name: db-stats
    restart: always
    environment:
      - POSTGRES_DB=statdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5431:5432"

  main-service:
    ports:
      - "8080:8080"
    build: ./main-service
    image: main-service-image
    container_name: ewm-server
    depends_on:
      - main-service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123

  main-service-db:
    container_name: main-service-db
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123